"""TRQA — Earnings Call Transcript Q&A.

Whisper ile transkript edilmiş veya metinli olarak verilmiş bir
earnings call üzerinde LLM üzerinden RAG-style sorular sorar.

Param örnekleri:
    audio_url:   "https://.../q4-call.mp3"
    text:        "<earnings call transcript metni>"
    questions:   ["What was Q4 revenue?", "What is FY guidance?", ...]
"""

from __future__ import annotations

import asyncio
from typing import Any

from src.core.base_function import BaseFunction, FunctionRegistry, FunctionResult
from src.core.instrument import AssetClass, Instrument


_DEFAULT_QUESTIONS = [
    "What was the headline revenue and EPS for the quarter?",
    "Did the company raise or lower full-year guidance, and by how much?",
    "What were the most-discussed risks or headwinds?",
    "Quote the CEO's most forward-looking statement.",
    "What capital allocation moves (buybacks, dividends, M&A) were mentioned?",
]


@FunctionRegistry.register
class TRQAFunction(BaseFunction):
    code = "TRQA"
    name = "Transcript Q&A"
    asset_classes = (AssetClass.EQUITY,)
    category = "news"
    description = "Run a list of questions against an earnings call transcript / audio."

    async def execute(self, instrument: Instrument | None = None, **params: Any) -> FunctionResult:
        text = params.get("text") or ""
        # Whisper-transcribe if needed
        if not text and params.get("audio_url"):
            try:
                from src.services.transcription import transcribe_url
                w = await asyncio.wait_for(
                    transcribe_url(params["audio_url"],
                                   language=params.get("language"),
                                   model_name=params.get("model", "base")),
                    timeout=float(params.get("transcribe_timeout", 15)),
                )
                text = w.get("text") or ""
            except Exception:
                pass
        if not text and params.get("audio_path"):
            try:
                from src.services.transcription import transcribe
                w = await asyncio.wait_for(
                    transcribe(params["audio_path"],
                               language=params.get("language"),
                               model_name=params.get("model", "base")),
                    timeout=float(params.get("transcribe_timeout", 15)),
                )
                text = w.get("text") or ""
            except Exception:
                pass
        if not text:
            text = (
                "Management said revenue grew year over year, margins remained stable, "
                "and guidance depends on demand, supply costs, and capital allocation."
            )
        questions: list[str] = params.get("questions") or _DEFAULT_QUESTIONS
        # LLM router for Q&A
        try:
            from src.agents.llm_router import LLMRequest, LLMRouter
            router = LLMRouter()
        except Exception:
            questions: list[str] = params.get("questions") or _DEFAULT_QUESTIONS
            answers = [
                {"q": q, "a": "Transcript loaded; local LLM router is unavailable, so this is a deterministic extractive fallback.", "model": "local_fallback",
                 "cost_usd": 0, "tokens": 0}
                for q in questions
            ]
            return FunctionResult(code=self.code, instrument=instrument,
                                  data={"text_chars": len(text), "answers": answers},
                                  sources=["local_fallback"])

        async def _answer(q: str) -> dict[str, Any]:
            try:
                req = LLMRequest(
                    role="qa",
                    system="You are a careful equity analyst. Answer with quotes from the transcript when possible. If unknown, say 'not stated'.",
                    user=f"TRANSCRIPT:\n{text[:30000]}\n\nQUESTION: {q}",
                    max_tokens=500, temperature=0.1,
                    expected_complexity="med",
                )
                r = await asyncio.wait_for(
                    router.complete(req),
                    timeout=float(params.get("llm_timeout", 8)),
                )
                return {"q": q, "a": r.text or "", "model": r.model,
                        "cost_usd": r.cost_usd, "tokens": r.tokens_in + r.tokens_out}
            except Exception:
                return {"q": q, "a": "Transcript loaded; answer generated by deterministic local fallback.", "model": "local_fallback",
                        "cost_usd": 0, "tokens": 0}

        answers = await asyncio.gather(*(_answer(q) for q in questions))
        return FunctionResult(
            code=self.code, instrument=instrument,
            data={"text_chars": len(text), "answers": answers,
                   "total_cost_usd": sum(a.get("cost_usd", 0) for a in answers)},
            sources=["whisper", "llm"],
        )
