#!/usr/bin/env node
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import postcss from "postcss";

const ROOT = resolve(new URL("..", import.meta.url).pathname);
const DESIGN_SRC =
  process.env.SHOWME_DESIGN_SRC ||
  "/Users/nazmi/Desktop/ShowMe_Designs_2026-05-16/conversation-2-ShowMe-0.01-019e2b82/src";
const OUT_DIR = resolve(ROOT, "ui/src/design-export");
const OUT_TSX = join(OUT_DIR, "showme-design-export.tsx");
const OUT_CSS = join(OUT_DIR, "showme-design-export.css");

const SPECIAL_CODE_MAP = {
  PortOpt: "PORT_OPT",
  PortWhatif: "PORT_WHATIF",
  Form4: "FORM4",
  Gc3d: "GC3D",
};

function pascalToCode(name) {
  return SPECIAL_CODE_MAP[name] ?? name.toUpperCase();
}

function read(name) {
  return readFileSync(join(DESIGN_SRC, name), "utf8")
    .replace(/\r\n/g, "\n")
    .replace(/PRINT > /g, "PRINT &gt; ");
}

function asDesignWindowSource(name) {
  let text = read(name);
  if (name === "settings74.jsx") {
    text = text.replace(
      `    { id: "matrix",   nm: "Matrix",   hint: "CRT mono",
      stops: ["#000000", "#040b06", "#00ff41"] },
`,
      `    { id: "matrix",   nm: "Matrix",   hint: "CRT mono",
      stops: ["#000000", "#040b06", "#00ff41"] },
    { id: "neon",    nm: "Neon",    hint: "Electric",
      stops: ["#000000", "#0a0a0a", "#39ff14"] },
`,
    );
  }
  return text
    .replace(
      /\bwindow\.([A-Za-z0-9_]+)\s*=\s*function\s+([A-Za-z0-9_]+)\s*\(/g,
      "const $2 = DESIGN_WINDOW.$1 = function $2(",
    )
    .replace(/\bwindow\./g, "DESIGN_WINDOW.");
}

function pageIndex(name) {
  const match = name.match(/^pages(\d*)-(basic|pro)\.jsx$/);
  if (!match) return null;
  return match[1] === "" ? 1 : Number(match[1]);
}

function collectPageGroups() {
  const files = readdirSync(DESIGN_SRC).filter((name) => /^pages\d*-(basic|pro)\.jsx$/.test(name));
  const groups = new Map();
  for (const name of files) {
    const idx = pageIndex(name);
    if (idx == null) continue;
    const group = groups.get(idx) ?? {};
    if (name.includes("-basic")) group.basic = name;
    else group.pro = name;
    groups.set(idx, group);
  }
  return [...groups.entries()].sort((a, b) => a[0] - b[0]);
}

function collectWindowComponentNames(files) {
  const basic = new Map();
  const pro = new Map();
  const settings = new Map();
  for (const name of files) {
    const text = read(name);
    for (const match of text.matchAll(/\bwindow\.(Basic|Pro)([A-Za-z0-9_]+)\s*=/g)) {
      const [, variant, pascal] = match;
      const code = pascalToCode(pascal);
      (variant === "Basic" ? basic : pro).set(code, `${variant}${pascal}`);
    }
    for (const match of text.matchAll(/\bwindow\.(Settings[A-Za-z0-9_]+|SetSidebar)\s*=/g)) {
      const name = match[1];
      if (name.startsWith("Settings")) settings.set(name.replace(/^Settings/, "").toUpperCase(), name);
    }
  }
  return { basic, pro, settings };
}

function renderMap(name, map) {
  const lines = [...map.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, component]) => `  ${JSON.stringify(code)}: DESIGN_WINDOW.${component},`);
  return `const ${name}: Record<string, DesignComponent | undefined> = {\n${lines.join("\n")}\n};`;
}

function renderCodeList(name, map) {
  const codes = [...map.keys()].sort((a, b) => a.localeCompare(b));
  return `export const ${name} = ${JSON.stringify(codes)} as const;`;
}

function buildTsx() {
  const pageGroups = collectPageGroups();
  const groupedPageFiles = pageGroups.flatMap(([, group]) => [group.basic, group.pro].filter(Boolean));
  const componentFiles = [
    "basic.jsx",
    "pro.jsx",
    "catalog.jsx",
    ...groupedPageFiles,
    "settings74.jsx",
    "settings75.jsx",
    "settings76.jsx",
  ];
  const { basic, pro, settings } = collectWindowComponentNames(componentFiles);

  const chunks = [];
  chunks.push(`/* AUTO-GENERATED by scripts/generate_design_export.mjs. Do not edit by hand. */`);
  chunks.push(`// @ts-nocheck`);
  chunks.push(`import * as React from "react";`);
  chunks.push(`import { readState, type Preset } from "@/lib/theme";`);
  chunks.push(`import "./showme-design-export.css";`);
  chunks.push(``);
  chunks.push(`type DesignComponent = React.ComponentType<{ theme: string }>;`);
  chunks.push(`const DESIGN_WINDOW: Record<string, any> = {};`);
  chunks.push(``);
  chunks.push(read("data.js").replace(/\bwindow\.SM_DATA\s*=/, "const SM_DATA ="));
  chunks.push(read("data-fns.js").replace(/\bwindow\.SM_FNS\s*=/, "const SM_FNS ="));
  chunks.push(``);
  chunks.push(`/* Shared Basic shell primitives from Design export. */`);
  chunks.push(asDesignWindowSource("basic.jsx"));
  chunks.push(``);
  chunks.push(`/* Shared Pro shell primitives from Design export. */`);
  chunks.push(asDesignWindowSource("pro.jsx"));
  chunks.push(``);
  chunks.push(`/* Function catalog artboards. */`);
  chunks.push(`(() => {\n${asDesignWindowSource("catalog.jsx")}\n})();`);
  chunks.push(``);
  for (const [idx, group] of pageGroups) {
    const parts = [group.basic, group.pro].filter(Boolean);
    chunks.push(`/* Function artboard group ${idx}. */`);
    chunks.push(`(() => {\n${parts.map(asDesignWindowSource).join("\n\n")}\n})();`);
    chunks.push(``);
  }
  chunks.push(`/* Settings artboards. */`);
  chunks.push(`(() => {\n${["settings74.jsx", "settings75.jsx", "settings76.jsx"].map(asDesignWindowSource).join("\n\n")}\n})();`);
  chunks.push(``);
  chunks.push(renderMap("DESIGN_BASIC", basic));
  chunks.push(renderMap("DESIGN_PRO", pro));
  chunks.push(renderMap("DESIGN_SETTINGS", settings));
  chunks.push(renderCodeList("DESIGN_BASIC_CODES", basic));
  chunks.push(renderCodeList("DESIGN_PRO_CODES", pro));
  chunks.push(renderCodeList("DESIGN_SETTINGS_CODES", settings));
  chunks.push(`
const EXPORT_THEMES = new Set(["midnight", "matrix", "iced", "amber", "papyrus", "neon"]);
const EXPORT_THEME_LABELS: Record<string, Preset> = {
  Midnight: "midnight",
  Matrix: "matrix",
  Iced: "iced",
  Amber: "amber",
  Papyrus: "papyrus",
  Neon: "neon",
};

function currentExportTheme(): string {
  if (typeof document !== "undefined") {
    const preset = document.documentElement.getAttribute("data-preset");
    if (preset && EXPORT_THEMES.has(preset)) return preset;
  }
  const state = readState();
  return EXPORT_THEMES.has(state.preset) ? state.preset : "papyrus";
}

export function hasDesignExportComponent(code: string): boolean {
  const key = code.toUpperCase();
  return !!(DESIGN_PRO[key] || DESIGN_BASIC[key]);
}

export function getDesignExportComponent(code: string, variant: "basic" | "pro" = "pro"): DesignComponent | null {
  const key = code.toUpperCase();
  return (variant === "basic" ? DESIGN_BASIC[key] || DESIGN_PRO[key] : DESIGN_PRO[key] || DESIGN_BASIC[key]) ?? null;
}

function themePresetFromCard(target: EventTarget | null): Preset | null {
  if (!(target instanceof Element)) return null;
  const card = target.closest(".sm-set__theme");
  if (!card) return null;
  const label = card.querySelector(".label .nm")?.textContent?.trim() ?? "";
  return EXPORT_THEME_LABELS[label] ?? null;
}

function settingsSectionFromNav(target: EventTarget | null): string | null {
  if (!(target instanceof Element)) return null;
  const item = target.closest(".sm-set__navitem");
  if (!item) return null;
  const labelNode = item.querySelector(".nm")?.childNodes[0];
  const label = labelNode?.textContent?.trim().toLowerCase() ?? "";
  return {
    appearance: "appearance",
    data: "data",
    streams: "streams",
    secrets: "secrets",
    migration: "migration",
    llm: "llm",
    about: "about",
  }[label] ?? null;
}

export function DesignExportRenderer({ code, variant = "pro" }: { code: string; symbol?: string; variant?: "basic" | "pro" }) {
  const Component = getDesignExportComponent(code, variant);
  if (!Component) return null;
  return (
    <div className="design-export" data-design-code={code.toUpperCase()} data-design-variant={variant}>
      <Component theme={currentExportTheme()} />
    </div>
  );
}

export function SettingsDesignExportRenderer({ section, onPreset, onSection, chromeOnly = false }: { section: string; onPreset?: (preset: Preset) => void; onSection?: (section: string) => void; chromeOnly?: boolean }) {
  const handleClick = React.useCallback((event: React.MouseEvent<HTMLDivElement>) => {
    const nextSection = settingsSectionFromNav(event.target);
    if (nextSection && onSection) {
      onSection(nextSection);
      return;
    }
    if (section.toUpperCase() !== "APPEARANCE" || !onPreset) return;
    const preset = themePresetFromCard(event.target);
    if (preset) onPreset(preset);
  }, [onPreset, onSection, section]);

  const Component = DESIGN_SETTINGS[section.toUpperCase()];
  if (!Component) return null;
  if (chromeOnly) {
    const Sidebar = DESIGN_WINDOW.SetSidebar as React.ComponentType<{ active: string }>;
    return (
      <div className="design-export" data-design-code={section.toUpperCase()} data-design-variant="settings-chrome" onClick={handleClick}>
        <div className="sm-root sm-set sm-set--chrome-only" data-theme={currentExportTheme()}>
          <Sidebar active={section.toLowerCase()} />
        </div>
      </div>
    );
  }
  return (
    <div className="design-export" data-design-code={section.toUpperCase()} data-design-variant="settings" onClick={handleClick}>
      <Component theme={currentExportTheme()} />
    </div>
  );
}
`);
  return chunks.join("\n\n");
}

function prefixSelector(selector) {
  const trimmed = selector.trim();
  if (!trimmed) return selector;
  if (trimmed === ":root") return ".design-export";
  if (trimmed.includes(":root")) return trimmed.replaceAll(":root", ".design-export");
  if (trimmed.startsWith(".design-export")) return trimmed;
  return `.design-export ${trimmed}`;
}

function buildCss() {
  const cssFiles = readdirSync(DESIGN_SRC)
    .filter((name) => /\.css$/.test(name))
    .sort((a, b) => {
      const order = ["themes.css", "basic.css", "pro.css", "settings.css", "pages.css"];
      const ia = order.indexOf(a);
      const ib = order.indexOf(b);
      if (ia !== -1 || ib !== -1) return (ia === -1 ? 999 : ia) - (ib === -1 ? 999 : ib);
      return a.localeCompare(b, undefined, { numeric: true });
    });
  const source = cssFiles.map((name) => `/* ${basename(name)} */\n${read(name)}`).join("\n\n");
  const root = postcss.parse(source, { from: undefined });
  root.walkRules((rule) => {
    const parentName = rule.parent?.type === "atrule" ? rule.parent.name : "";
    if (/keyframes/i.test(parentName)) return;
    rule.selectors = rule.selectors.map(prefixSelector);
  });
  return `/* AUTO-GENERATED by scripts/generate_design_export.mjs. Do not edit by hand. */\n.design-export {\n  position: relative;\n  width: 100%;\n  height: 100%;\n  min-height: 720px;\n  overflow: hidden;\n  isolation: isolate;\n}\n\n.design-export .sm-set__theme {\n  cursor: pointer;\n}\n\n${root.toString()}\n`;
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_TSX, buildTsx());
writeFileSync(OUT_CSS, buildCss());
console.log(`generated ${OUT_TSX}`);
console.log(`generated ${OUT_CSS}`);
